---
aliases:
  k: 'kubectl'
  kcset: "kubectl config use-context $1"
  kcunset: "kubectl config unset current-context"
  kcshow: "kubectl config get-contexts"
  ssh: "/usr/bin/ssh -A"
  drc: 'docker-compose'
  
env:
  PKG_CONFIG_PATH: "/usr/local/Cellar/libvirt/4.5.0/lib/pkgconfig"
  


# fabulous: 'yes "$(seq 231 -1 16)" | while read i; do printf "\x1b[48;5;    ${i}m\n"; sleep .02; done'

