---
- name: check if homebrew is already installed
  stat:
    path: /usr/local/bin/brew
  register: hb

- name: install homebrew if not exists
  script: install-homebrew.sh
  when: not hb.stat.exists

- homebrew:
    name: "{{ item }}"
    state: latest
    update_homebrew: yes
  with_items:
    - bat
    - prettyping
    - zsh
    - jq
    - gpg
    - httpie
    - ipmitool
    - git
    - htop
    - diff-so-fancy
    - vim 
    - fd
    - fzf
    - ncdu
    - python3
    - screenfetch
    - mtr
    - keychain
    - ack
    - lnav
    - kubernetes-cli
    - yq
    - wget
    - kubernetes-helm
    - miller
    - ipcalc
    - zsh
    - zsh-completions
    - jsonlint
    - telnet
    - tmux
    - expect
    - ansible-lint
    - rakudo-star
    - libusb
    - ctags
    - molecule
    - flake8
  tags:
    - homebrew

- homebrew_cask:
   name: "{{ item }}"
   state: present
   update_homebrew: yes
   upgrade_all: true
  with_items:
    - keepingyouawake
    - macdown
  tags:
    - homebrew

- homebrew_tap:
   name: "{{ item }}"
   state: present
   update_homebrew: yes
   upgrade_all: true
  with_items:
    - zaquestion/tap/lab
  tags:
    - homebrew

- name: mac dotfile setup
  template: 
    src: "dotfiles/macos/{{ item }}"
    dest: "/Users/jkl/.{{ item }}"
  with items:
    - zshrc
  tags: 
    - dots-mac

# set up some defaults ootb
- name: MacOS: disable smart quotes
  osx_defaults:
    domain: NSGlobalDomain
    key: NSAutomaticQuoteSubstitutionEnabled
    type: bool
    value: false

- name: MacOS Services: don't write .DS_Store files on removable drives
  osx_defaults:
    domain: com.apple.desktopservices
    key: DSDontWriteUSBStores
    type: bool
    value: false

- name: MacOS Services: don't write .DS_Store files on network drives
  osx_defaults:
    domain: com.apple.desktopservices
    key: DSDontWriteNetworkStores
    type: bool
    value: false

- name: Finder: don't warn before emptying trash
  osx_defaults:
    domain: com.apple.finder
    key: WarnOnEmptyTrash
    type: bool
    value: false

- name: Finder: use list view by default
  osx_defaults:
    domain: com.apple.finder
    key: FXPreferredViewStyle
    type: string
    value: "Nlsv"

- name: Finder: disable warning on file extension change
  osx_defaults:
    domain: com.apple.finder
    key: FXEnableExtensionChangeWarning
    type: bool
    value: false

- name: Finder: enable path bar
  osx_defaults:
    domain: com.apple.finder
    key: ShowPathbar
    type: bool
    value: true

- name: Dock: Auto-Hide the dock
  osx_defaults:
    domain: com.apple.dock
    key: autohide
    type: bool
    value: true

- name: Dock: Don't show recent applications
  osx_defaults:
    domain: com.apple.dock
    key: show-recents
    type: bool
    value: false

 
